class MandelbrotSet:
    escape_radius: int
    max_iteration: int
    def __init__(self, escape_radius: int, max_iteration: int) -> None: ...
    def __contains__(self, c: complex) -> bool: ...
    def stability(self, c: complex, smooth: bool, clamp: bool) -> float: ...
    def get_iteration_count(self, c: complex, smooth: bool) -> float: ...
